version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017

  node:
    build: .
    container_name: node_app_container
    ports:
      - 3000:3000
    platform: linux/x86_64
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/BigTrade

volumes:
  mongodb_data_container: